version: '3.4'

# envs https://medium.com/softonic-eng/docker-compose-from-development-to-production-88000124a57c

services:

  # https://hub.docker.com/_/postgres/
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    ports:
    - "5432:5432"
    networks:
      - postgres

  feedless-agent:
    image: damoeb/feedless:agent-0.1
#    deploy:
#      replicas: 2
    security_opt:
      - seccomp=./chrome.json
    restart: unless-stopped
    environment:
      - APP_EMAIL=${APP_ROOT_EMAIL}
      - APP_SECRET_KEY=${APP_ROOT_SECRET_KEY}
      - APP_HOST=feedless-core:8080
      - APP_SECURE=false
    ports:
      - "3000:3000"
#    healthcheck:
#      test: curl -f https://localhost:3000 || exit 1

  feedless-app:
    image: damoeb/feedless:app-0.1
    restart: unless-stopped
    ports:
      - "4200:80"

  feedless-core:
    image: damoeb/feedless:core-0.1
    restart: unless-stopped
#    healthcheck:
#      test: curl -f https://localhost:8080 || exit 1
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - APP_DATABASE_URL=jdbc:postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - APP_ACTIVE_PROFILES=database
      - APP_WHITELISTED_HOSTS=feedless-core
      - AUTH_TOKEN_ANONYMOUS_VALIDFORDAYS=3
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
